### ISSUE TITLE
Does not work with custom metrics

### ISSUE THREAD

**Issue by stevemao** [open-telemetry/opentelemetry-lambda-extension#1135]
**Describe the bug**

Metrics is not exported.

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

Step 1. follow
https://opentelemetry.io/docs/faas/lambda-auto-instrument/
All default config. everything should be exported to log which should be visible on cloudwatch

Step 2.
Add 

```ts
import { metrics } from '@opentelemetry/api';

// Create a meter
export const meter = metrics.getMeter('your-metric-name');

// Define a counter metric
export const requestCounter = meter.createCounter('my-requests', {
  description: 'Counts number of requests processed',
});

requestCounter.add(1, { functionName: context.functionName });
```

In my lambda

**What did you expect to see?**
A clear and concise description of what you expected to see.

metrics in log which should be in cloudwatch

**What did you see instead?**
A clear and concise description of what you saw instead.

Only traces in the log, no metrics

**What version of collector/language SDK version did you use?**
Version: (e.g., `v0.58.0`, `v1.11.0`, etc)

latest

**What language layer did you use?**
Config: (e.g., `Java`, `Python`, etc)

Nodejs

**Additional context**

**Comment by stevemao** [comment]
I notice it says Flush MeterProvider for nodejs is supported. so metrics should be flushed at the end of execution

**Comment by stevemao** [comment]
after https://github.com/open-telemetry/opentelemetry-lambda/pull/1136/files, it seems that logging works. But changing it to awsemf won't work. enable debugging by OTEL_LOG_LEVEL: 'DEBUG' won't log anything.

**Comment by serkan-ozal** [comment]
I think this might be fixed by https://github.com/open-telemetry/opentelemetry-lambda/pull/1504. 

@pragmaticivan WDYT?

**Comment by pragmaticivan** [comment]
👋🏽 I noticed that the metrics instrumented by the auto-instrumentation packages are working because they register the current meger provider. So My last PR #1504 sets a global provider with the same reference which will allow us to create custom metrics in the code and use the same flush/view setup of the lambda layer.
