### ISSUE TITLE
How to disable AwsInstrumentation?

### ISSUE THREAD

**Issue by onhate** [open-telemetry/opentelemetry-lambda-extension#1171]
While wanting to use open telemetry on aws lambda I don't want aws sdk spans and metrics, I would like to have only my custom (business) metrics sent to the server.

As of now I see the wrapper is hardcoded to include the AwsInstrumentation always, but I wonder if there is a way to disable that without opening a PR

**Comment by tylerbenson** [comment]
Could you use just the collector layer and not the JS layer?  Then you'd have the control to construct your own SDK instance and manually instrument your app as you wish.

**Comment by onhate** [comment]
I ended doing that, creating my custom wrapper, but in any case it's decided that it's a good feature to add the PR is ready to review :)

**Comment by tylerbenson** [comment]
Closing this for now.  Can revisit if we decide to add this consistently to all languages. For now, prefer using just the collector layer without the auto instrumentation layer.
