### ISSUE TITLE
Add `decouple` processor to the default config

### ISSUE THREAD

**Issue by nslaughter** [open-telemetry/opentelemetry-lambda-extension#1196]
**Is your feature request related to a problem? Please describe.**
Without the `decouple` processor in the pipeline there have been lengthy delays waiting on the Collector layer to flush telemetry. The [README explains](https://github.com/open-telemetry/opentelemetry-lambda/blob/collector/README.md) the situation.

**Describe the solution you'd like**
Add `decouple` processor to the default pipeline config. This is just adopting a sensible default that's more likely to benefit the community as a whole and will not limit the opportunity of users who disagree with the approach to override for the present state.

**Describe alternatives you've considered**
The current approach is to document for users how to override default config. This doesn't seem like the right approach given the significant benefit of using the `decouple` processor.

**Additional context**
I don't currently have the comparison data accessible, however this has been the subject of some research in the community and I can add details for discussion.

**Comment by xThomo** [comment]
You linked the Makefile in the issue description, I think you meant this [README](https://github.com/open-telemetry/opentelemetry-lambda/blob/597b0d31405d28083d4100f96aef3c0ca1e1c096/collector/README.md#improving-lambda-responses-times)

Any idea when #1197 will be merged? It looks like a simple change.

**Comment by nslaughter** [comment]
> You linked the Makefile in the issue description, I think you meant this [README](https://github.com/open-telemetry/opentelemetry-lambda/blob/597b0d31405d28083d4100f96aef3c0ca1e1c096/collector/README.md#improving-lambda-responses-times)
> 
> Any idea when #1197 will be merged? It looks like a simple change.

Thanks for the correction and the interest in #1197. What's happened here is an intervening idea where the decoupleprocessor could be added to the end of pipelines which contain a batch processor. I've written up the [code for that in my fork](https://github.com/nslaughter/opentelemetry-lambda/pull/1) and will be documenting it better before sharing for approval next week.

**Comment by nslaughter** [comment]
Addressed in #1255
