### ISSUE TITLE
`xray-lambda` Implementation Progress

### ISSUE THREAD

**Issue by tylerbenson** [open-telemetry/opentelemetry-lambda-extension#1228]
Tracking issue for the implementation of this specification: https://github.com/open-telemetry/semantic-conventions/blob/main/docs/faas/aws-lambda.md#xray-lambda-propagator-functionality

- [x] Java
  - https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1032
  - https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10930
- [x] Javascript
  - https://github.com/open-telemetry/opentelemetry-js/pull/4554
  - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2299
  - https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2369
- [x] Python
  - https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2573
  - https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2599

Other languages don't currently have published community layers so aren't listed.

**Comment by gshpychka** [comment]
@tylerbenson should be updated, looks like the PRs were merged

**Comment by tylerbenson** [comment]
Thanks for the reminder.  I've updated it a bit.

**Comment by tylerbenson** [comment]
I think this is ready to close out with the latest addition to js-contrib. I'll do so when it's released and added to a layer.

**Comment by tylerbenson** [comment]
I believe this is done... everything has been released.
