### ISSUE TITLE
Inconsistent Java Version Support Documentation

### ISSUE THREAD

**Issue by arun-annamalai** [open-telemetry/opentelemetry-lambda-extension#1295]
**Describe the bug**

In the following docs, Java8,11,17 are supported by the Java Auto Instrumentation Layer: https://opentelemetry.io/docs/faas/lambda-auto-instrument/

In the following docs, it only says Java11 is supported. https://github.com/open-telemetry/opentelemetry-lambda/blob/main/java/README.md

**What did you expect to see?**
A clear and concise description of what you expected to see.
There needs to be clarity around what versions of Java that the Java Wrapper Layer supporters and that the Java Auto Instrumentation Layer Supports. 

**What language layer did you use?**
Java

**Comment by tylerbenson** [comment]
I believe 8, 11, and 17 are supported.  Would you like to open a PR to correct the README?

**Comment by arun-annamalai** [comment]
yes I will submit a PR for this. Thanks!
