### ISSUE TITLE
Dead links to OTEL documentation

### ISSUE THREAD

**Issue by Kevinwochan** [open-telemetry/opentelemetry-lambda-extension#1384]
**Describe the bug**
Links in the main documentation for traces and metrics have fallen out of date

| Feature                    | Node | Python | Java | .NET | Go   | Ruby |
| -------------------------- | :--: | :----: | :--: | :--: | :--: | :--: |
| OpenTelemetry collector    |  +   |  +     |  +   |  +   |  +   |  +   |
| Custom context propagation |  +   |  -     |  -   |  -   | N/A  |  +   |
| X-Ray Env Var Span Link    |  -   |  -     |  -   |  -   | N/A  |  -   |
| Semantic Conventions^      |      |  +     |  +   |  +   | N/A  |  +   |
| - Trace General^<sup>[1]</sup>           |  +   |        |  +   |  +   | N/A  |   +  |
| - Trace Incoming^<sup>[2]</sup>          |  -   |        |  -   |  +   | N/A  |   -  |
| - Trace Outgoing^<sup>[3]</sup>          |  +   |        |  -   |  +   | N/A  |   +  |
| - Metrics^<sup>[4]</sup>                 |  -   |        |  -   |  -   | N/A  |   -  |
| Auto instrumentation       |      |   +    |  +   |  -   | N/A  |   +  |
| Flush TracerProvider       |  +   |   +    |      |  +   |  +   |   +  |
| Flush MeterProvider        |  +   |   +    |      |      |      |   -  |

[1]: https://github.com/open-telemetry/semantic-conventions/blob/main/docs/faas/faas-spans.md#general-attributes
[2]: https://github.com/open-telemetry/semantic-conventions/blob/main/docs/faas/faas-spans.md#incoming-invocations
[3]: https://github.com/open-telemetry/semantic-conventions/blob/main/docs/faas/faas-spans.md#outgoing-invocations
[4]: https://github.com/open-telemetry/semantic-conventions/blob/main/docs/faas/faas-metrics.md

**Comment by nslaughter** [comment]
Closing as resolved by #1385
