### ISSUE TITLE
Collector ships with deprecated logging exporter, not the modern debug exporter

### ISSUE THREAD

**Issue by lpetrazickisupgrade** [open-telemetry/opentelemetry-lambda-extension#1408]
**Describe the bug**
The OpenTelemetry Lambda layer docs say to use the `debug` exporter: https://opentelemetry.io/docs/faas/lambda-collector/

However, the collector layer ships with the deprecated `logging` exporter, not the current `debug` exporter: https://github.com/open-telemetry/opentelemetry-lambda/blob/layer-collector/0.8.0/collector/go.mod#L148

**Steps to reproduce**
Include configuration for the `debug` exporter:
```yaml
exporters:
  debug:
```

**What did you expect to see?**
A working OpenTelemetry Collector layer.

**What did you see instead?**
```json
{
  "level": "info",
  "ts": 1719433288.313658,
  "msg": "done",
  "error": "unable to start, otelcol state is 3; request failed with status 403 Forbidden",
  "errorCauses": [
    {
      "error": "unable to start, otelcol state is 3"
    },
    {
      "error": "request failed with status 403 Forbidden"
    }
  ]
}
{
  "level": "warn",
  "ts": 1719433288.8894677,
  "logger": "lifecycle.manager",
  "msg": "Failed to start the extension",
  "error": "failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:\n\n* error decoding 'exporters': unknown type: \"debug\" for id: \"debug\" (valid values: [logging otlp otlphttp prometheusremotewrite])"
}

```

**What version of collector/language SDK version did you use?**
Version: layer-collector/0.8.0 with v0.102.1

**What language layer did you use?**
Config: Python

**Additional context**
I'm attempting to use the layers in a container lambda, so I'm building the git tags locally to add to the container image

**Comment by avtar-cashify** [comment]
tried with `layer-collector/0.10.0` and `layer-python/0.9.0` same issue

**Comment by serkan-ozal** [comment]
@tylerbenson I think, 
- to be backward compatible, we still need to have `logging` exporter, but deprecate it until the next major release of the Lambda collector
- add `debug` exporter (https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/debugexporter) in the same way with `logging` exporter

**Comment by tylerbenson** [comment]
I'm fine with this.  Just need someone to implement it.

**Comment by tommyorndorff** [comment]
This is my first contribution. If you could give me some feedback on what else I'd need to do, I'm happy to sort it out. Thanks 🤙

**Comment by tommyorndorff** [comment]
Sorry about the multiple PRs -- my personal and work github accounts were fouling up the EasyCLA integration.
