### ISSUE TITLE
Private tokens could appear in logs if context containing gRPC metadata is logged in github.com/grpc/grpc-go

### ISSUE THREAD

**Issue by shenyutong10086** [open-telemetry/opentelemetry-lambda-extension#1423]
**Describe the bug**
This issue represents a potential PII concern. If applications were printing or logging a context containing gRPC metadata, the affected versions will contain all the metadata, which may include private information.

**Steps to reproduce**
The issue first appeared in 1.64.0 and is patched in 1.64.1 and 1.65.0

**What did you expect to see?**
If using an affected version and upgrading is not possible, ensuring you do not log or print contexts will avoid the problem.

**Comment by johnli-developer** [comment]
Please assign this to me

**Comment by johnli-developer** [comment]
The bot already created a PR https://github.com/open-telemetry/opentelemetry-lambda/pull/1420
