### ISSUE TITLE
Consider removing support to java8 runtime

### ISSUE THREAD

**Issue by rapphil** [open-telemetry/opentelemetry-lambda-extension#1442]
**Describe the bug**
Java8 support is reaching end of the life. No new function can be created with the Java8 runtime.
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtimes-deprecated

**Steps to reproduce**
Try to create a new function that uses java8.

**What did you expect to see?**
That opentelemetry-lambda did not support java8.

**What did you see instead?**
Java8 is still supported. 

**Additional context**
It is ok to deprecate java8 in my opinion because we still will support java8.al2.
https://aws.amazon.com/blogs/compute/announcing-migration-of-the-java-8-runtime-in-aws-lambda-to-amazon-corretto/

**Comment by tylerbenson** [comment]
Sounds reasonable to me.

**Comment by knarfli** [comment]
I want to take a look into it.

**Comment by rapphil** [comment]
@knarfli feel free to take a look into it. It should be a simple change in our release scripts. Thanks for the interest.

**Comment by knarfli** [comment]
Thanks @rapphil , I am working on that and will create a PR.

**Comment by serkan-ozal** [comment]
I agree on this too. I think, we will just remove `java8` from supported runtimes in the layer, right? Is there anything to do?

**Comment by tylerbenson** [comment]
I think that's all that's required.

**Comment by knarfli** [comment]
yes, agree with that, I have raised a pull request in a forked repository, but I need to follow some steps which block making the pull request here, let me try to speed it up.

**Comment by knarfli** [comment]
Pull request opened, https://github.com/open-telemetry/opentelemetry-lambda/pull/1481.
Please review.
