### ISSUE TITLE
Use `xray_lambda` in Python `OTEL_PROPAGATORS` environment variable

### ISSUE THREAD

**Issue by ocelotl** [open-telemetry/opentelemetry-lambda-extension#1445]
Please assign me this issue

**Comment by rapphil** [comment]
I think the default otel propagators are correct [here](https://github.com/open-telemetry/opentelemetry-lambda/blob/main/python/src/otel/otel_sdk/otel-instrument#L106) right? Since you closed the PR, can we close this issue as well?
