### ISSUE TITLE
Support sdk-logs for nodejs lambda wrapper

### ISSUE THREAD

**Issue by pragmaticivan** [open-telemetry/opentelemetry-lambda-extension#1458]
**Is your feature request related to a problem? Please describe.**
Hi there, in addition to metrics and traces, I would also like to send logs via https://github.com/open-telemetry/opentelemetry-js/tree/main/experimental/packages/sdk-logs

**Describe the solution you'd like**
Just add support for that, since the collector can deal with that now.

**Describe alternatives you've considered**
Instrument logs manually and send to the same collector.

**Comment by tylerbenson** [comment]
We don't have any active participants with Javascript expertise, so if you'd like to contribute please feel free.

**Comment by pragmaticivan** [comment]
@tylerbenson PR is up
