### ISSUE TITLE
Add NathanielRN to repo approvers

### ISSUE THREAD

**Issue by NathanielRN** [open-telemetry/opentelemetry-lambda-extension#151]
# Description

The AWS Observability team continues to make improvements to the OTel + AWS experience. I have had the chance to work on OpenTelemetry for the last year, and have made contributions to this repo as well. See:

#110 
#148
#150 
#124

I have experience contributing to OpenTelemetry repos, especially including OTel Python. Give all of this, I'm requesting to be added as an ~maintainer~ approver to this `opentelemetry-lambda` repo so I can help with reviews and have less resistance as I continue to work on new feature to the repo. I believe my experience will help me make positive contributions to this project.

Thank you! 🙂 

Tag @codeboten

**Comment by wangzlei** [comment]
+1

**Comment by anuraaga** [comment]
I think in most OTel repos, we generally start with adding to approvers and later after showing work on broad technical issues in that repo could step up to maintainer (initial bootstrapping of a repo may be lax here out of necessity). I think your work looks good for being added as an approver, how does that sound? It won't particularly address "have less resistance as I continue to work on new feature to the repo" but I hope having a team member and other members from AWS in maintainers will keep you unblocked.

For reference, here are the responsibilities for approver and maintainer.
https://github.com/open-telemetry/community/blob/main/community-membership.md#approver

**Comment by NathanielRN** [comment]
Sure! An approver role is fine with me. I'll update the issue description.

**Comment by anuraaga** [comment]
Cool! @codeboten I think you're the only one that can edit the teams, can you add @NathanielRN to https://github.com/orgs/open-telemetry/teams/lambda-extension-approvers/members? Also is it possible to set it so all the maintainers are able to do that?

**Comment by codeboten** [comment]
@NathanielRN added, also updated the group to ensure all maintainers can manage permissions
