### ISSUE TITLE
Config from an env var seems not to work

### ISSUE THREAD

**Issue by bobthemighty** [open-telemetry/opentelemetry-lambda-extension#1529]
**Describe the bug**

The env confmap provider apparently allows one to read a config file from an environment variable, ie.

```
OPENTELEMETRY_COLLECTOR_CONFIG_URI=env:MY_CONF
MY_CONF=receivers...
```

This does work on the downstream ADOT layer, but seems _not_ work with this layer. I can see that the confmap provider is included in the project, so am I doing something stupid? I don't want to use ADOT because a) it doesn't like the "batch" processor, and b) it regularly times out on init. To be fair, your docs mention that the URI can point to S3 or HTTP, but I don't have a good understanding of why this doesn't work if the env provider is in place.

**Steps to reproduce**

* Add a yaml file to an environment var "MY_BEST_CONFIG"
* Set the value of OPENTELEMETRY_COLLECTOR_CONFIG_URI to env:MY_BEST_CONFIG 
* Ship it.

**What did you expect to see?**
I expected to see my config applied

**What did you see instead?**
The default configuration was applied, I think.

**What version of collector/language SDK version did you use?**

- [layer-collector/0.10.0](https://github.com/open-telemetry/opentelemetry-lambda/releases/tag/layer-collector%2F0.10.0)

**What language layer did you use?**

- [layer-nodejs/0.9.0](https://github.com/open-telemetry/opentelemetry-lambda/releases/tag/layer-nodejs%2F0.9.0)

**Comment by tylerbenson** [comment]
@bobthemighty This is a recent change. I believe you'll need to wait for the next release (soon). Meanwhile, you can use the old setting.

Related: #1521
cc @gshpychka

**Comment by gshpychka** [comment]
> @bobthemighty This is a recent change. I believe you'll need to wait for the next release (soon). Meanwhile, you can use the old setting.
> 
> Related: #1521 cc @gshpychka

Yup. Would you like me to open a PR to call out the previous (but actually current, until the release) env var name in the docs?

**Comment by bobthemighty** [comment]
> you can use the old setting.

So I can! I was sure I'd tested that, but I now have telemetry in Honeycomb, and the world is a sunny and beautiful place once more. Apologies!

**Comment by tylerbenson** [comment]
@gshpychka don't worry about it.  We should have a new release soon.
