### ISSUE TITLE
Make the debug exporter work in the lambda collector

### ISSUE THREAD

**Issue by nslaughter** [open-telemetry/opentelemetry-lambda-extension#1552]
**Is your feature request related to a problem? Please describe.**
The capabilities of the `debug exporter` would be a valuable addition for custom builds.

**Describe the solution you'd like**
Provide this option for custom builds as well as default (#1520).

**Comment by nslaughter** [comment]
There is work done to enable this in #1551. The work to enable in default was done in #1520.

**Comment by serkan-ozal** [comment]
@nslaughter @tylerbenson it seems that we can close this issue?
