### ISSUE TITLE
Node.js lambda layer - instrumentation error

### ISSUE THREAD

**Issue by ghost** [open-telemetry/opentelemetry-lambda-extension#159]
Steps to reproduce:
- build and deploy layer
- create sample JS lambda
- add layer
- configure `AWS_LAMBDA_EXEC_WRAPPER`
Result: `Uncaught Exception {"errorType":"Runtime.ImportModuleError(...)`

The problem was fixed by https://github.com/open-telemetry/opentelemetry-js/pull/2450 which was released with `"@opentelemetry/instrumentation": "0.26.0"`. I manually changed the dependency and it works.

Propsed solution: 
- update `@opentelemetry/instrumentation` in `layer/package.json` to 0.26.0
- release new version of https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-aws-lambda - this also contains the instrumentation dependency version 0.25.0 (with bug unfortunately)

@anuraaga who could help with that? Especially releasing `opentelemetry-instrumentation-aws-lambda` - I'm green in this respect.

**Comment by anuraaga** [comment]
@kubawach Do we need a new release for opentelemetry-instrumentation-aws-lambda? It seems the currently released 0.26.0 does target 0.26.0 of opentelemetry/instrumentation, doesn't it?

https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-aws-lambda/package.json#L64

**Comment by ghost** [comment]
@anuraaga unfortunately the latest released version of the `opentelemetry-instrumentation-aws-lambda` package is 0.26.0 which uses instrumentation 0.25.0 (see https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/instrumentation-aws-lambda-v0.26.0). 
The package.json from your link is main - once we release it we should be good

**Comment by anuraaga** [comment]
I see - @willarmiros do you know the release process for that artifact? Do we generally release it ourselves when needed rather than waiting for the JS repo release?

**Comment by willarmiros** [comment]
We can release ourselves independent of the upstream JS schedule. We will plan a release in the near future and update this issue when it's out.

**Comment by ghost** [comment]
@willarmiros thanks, looking forward to :)

**Comment by ghost** [comment]
I see it's been done (0.27.0 depending on instrumentation 0.26.0): https://github.com/open-telemetry/opentelemetry-js-contrib/blob/instrumentation-aws-lambda-v0.27.0/plugins/node/opentelemetry-instrumentation-aws-lambda/package.json 
Closing the issue then.
