### ISSUE TITLE
Maintainer Access Request - NathanielRN

### ISSUE THREAD

**Issue by NathanielRN** [open-telemetry/opentelemetry-lambda-extension#219]
## Description

Follow up to #151

The AWS Observability team continues to make improvements to the OTel + AWS experience. Recently, the team added support for the arm64 architecture, added .NET and Go Sample Lambda Apps, updated languages to the latest language, etc. I have had the chance to work on OpenTelemetry for the last year, with several of my contributions being in this repo. This includes the following:

#204
#192
#196
#181
#110
#148
#150
#124

Since becoming an approver 3 months ago in #151, I have reviewed PRs, pushed out fixes, and helped move progress on this repo along. My experience with OpenTelemetry and this repo should help me be able to continue to help maintain it. For this reason, I'm **requesting to be added as an maintainer** with write access to this opentelemetry-lambda repo. I believe my experience will help me make positive contributions to this project's progress.

Thank you! 🙂

**Comment by alolita** [comment]
I support this @codeboten Adding @NathanielRN will help us maintain OTEL Lambda functionality so please consider this request.

**Comment by wangzlei** [comment]
I support @NathanielRN to be OTel Lambda maintainer. Please consider this request @codeboten

**Comment by codeboten** [comment]
@NathanielRN was added to the maintainers group 👍
