### ISSUE TITLE
[Feature Request]: Support for provided.al2

### ISSUE THREAD

**Issue by disfluxly** [open-telemetry/opentelemetry-lambda-extension#239]
Hello,

Are there any technical hurdles in adding in support for provided.al2 lambda runtimes? These would be needed for lambdas written in go, where the current runtime support is recommended to use provided.al2 as the AL1 go1.x runtime ended support in Dec 2020.

Is it as simple as just adding `provided.al2` to the Makefile here for supported runtimes: https://github.com/open-telemetry/opentelemetry-lambda/blob/main/collector/Makefile#L33

Or are there technical challenges that prevent the collector from working in this kind of scenario?

**Comment by RangelReale** [comment]
I'm looking for this also, is there any technical problem that there is no Go extension?

Looking at the [AWS Lambda Extensions repo](https://github.com/aws-samples/aws-lambda-extensions), there seems to be lots of Go samples for lambda extensions, they don't look special.

If someone can point me to the right direction, I can try to implement and contribute this.

**Comment by Aneurysm9** [comment]
I don't believe any changes are required to support `provided.al2`.  The [current Go sample applications](https://github.com/open-telemetry/opentelemetry-lambda/blob/1f36b901da88839fdfa28efcf1190e37e9f0fdcb/go/sample-apps/aws-sdk/deploy/wrapper/main.tf#L8) use that runtime.  The [ADOT distribution provides a layer](https://aws-otel.github.io/docs/getting-started/lambda/lambda-go) that can be used with `provided.al2` for Go-based functions.

**Comment by RangelReale** [comment]
I tested with `provided.al2`, and it worked without any changes, so I think this can be closed.
