### ISSUE TITLE
Update NodeJS layers

### ISSUE THREAD

**Issue by monken** [open-telemetry/opentelemetry-lambda-extension#247]
**Is your feature request related to a problem? Please describe.**

The current layer version 1.2.0 contains dated versions of instrumentation-aws-sdk and instrumentation-aws-lambda.

**Describe the solution you'd like**
Could we please get an updated layer? It would be great to have those layers published whenever any of the dependencies release a new version.

**Describe alternatives you've considered**
Building our own layer.

**Additional context**
NA

**Comment by vasireddy99** [comment]
The layers are updated to the latest available versions, Please confirm and close this issue :-)

**Comment by monken** [comment]
Thanks, I can see the new layers. Can this process be automated? It took several months and that is not ideal especially since critical updates are landing and not published as a layer which forces me to maintain my own layers (which I don't want to do).
