### ISSUE TITLE
Possibility of doing releases

### ISSUE THREAD

**Issue by garymartyn** [open-telemetry/opentelemetry-lambda-extension#271]
Hi all, 

Would it be possible to do releases in this repository?

We are planning to build and create AWS lambda layers,
Currently, it is a manual task to know when to build a new layer, by checking which, if any PRs have been merged.

Having releases would let us know when its stable to create a new layer

**Comment by Medik-GH** [comment]
+1 on this. Is there a reason for not doing releases?

**Comment by vasireddy99** [comment]
The releases or updates in the repo are currently happening on monthly cadence.

**Comment by Medik-GH** [comment]
@vasireddy99 Are you guys planning on doing GitHub Releases? I think that's what the original question was about.

**Comment by Medik-GH** [comment]
Considering we have releases now I think this can be closed @vasireddy99
