### ISSUE TITLE
Getting Runtime exited with error: exit status 127 with OTEL Layer installed

### ISSUE THREAD

**Issue by M3gar00** [open-telemetry/opentelemetry-lambda-extension#274]
I installed the OTEL Lambda Layer following the instructions [here](https://github.com/open-telemetry/opentelemetry-lambda/tree/main/python). When the script completed, there was no ARN for the lambda, so I had to go into AWS and manually retrieve the ARN.

With the Layer installed, I ran one of our lambdas and this error popped up.

```
{
  "errorMessage": "RequestId: 8f70eba2-4dbb-49b9-8e15-251ac74dc18d Error: Runtime exited with error: exit status 127",
  "errorType": "Runtime.ExitError"
}
```
According to what I've discovered about Lambda error 127 is that it's missing dependencies, but I don't see any obvious way of ensuring dependencies are met. Any suggestions? Alternate instructions?

**Comment by iulspop** [comment]
I got the same error using the [AWS managed Lambda Layer for ADOT Java Auto-instrumentation Agent and ADOT Collector](https://aws-otel.github.io/docs/getting-started/lambda/lambda-java-auto-instr):
```
{
  "errorType": "Runtime.ExitError",
  "errorMessage": "RequestId: 6d3458ba-efb3-4135-96f9-3d9b7f35499a Error: Runtime exited with error: exit status 127"
}
```

I don't know how to get a better error message or more information

**Comment by chiragdevx** [comment]
facing the same issue when I am tring to create lambda in golang using custom runtime

```

resource "aws_lambda_function" "product-handler" {
  function_name = "productHandler"
  handler       = "bootstrap"
  runtime       = "provided.al2"
  filename      = data.archive_file.zip_the_lambda_code["productHandler"].output_path
  role          = aws_iam_role.lambda_execution_role.arn

  source_code_hash = data.archive_file.zip_the_lambda_code["productHandler"].output_base64sha256

  lifecycle {
    create_before_destroy = true 
  }
}
```

**Comment by mldelaro** [comment]
If you're using AWS' ADOT Lambda Layer, ensure that you've set the `AWS_LAMBDA_EXEC_WRAPPER` env-var to the proper wrapper-script value. Setting the correct environment variable with the correct value resolved my issue:
```
AWS_LAMBDA_EXEC_WRAPPER = "/opt/otel-handler"
```
