### ISSUE TITLE
Conflict with others lambda layers

### ISSUE THREAD

**Issue by srenault** [open-telemetry/opentelemetry-lambda-extension#290]
This issue is related to opentelemetry-lamba for NodeJS.
My project is using Sentry to report all unhandled errors. We integrated Sentry into our project by using the official lambda [layer](https://docs.sentry.io/platforms/node/guides/aws-lambda/layer/). On top of it, we included this opentelemetry-lambda layer and we run into some issues. I was interested in the auto instrumentation opentelemetry provides, more specifically the one that collects traces regarding all http outgoing calls. It was not working and I figured out it was related to https://opentelemetry.io/blog/2022/troubleshooting-nodejs/#enable-before-require.
Afer some investigation, I understand sentry code was required before opentelemetry, mainly because of this https://github.com/open-telemetry/opentelemetry-lambda/blob/main/nodejs/packages/layer/scripts/otel-handler#L3.

Are there is any reasons why we don't define the ordering that way?
```bash
export NODE_OPTIONS="--require /opt/wrapper.js ${NODE_OPTIONS}"
```

**Comment by Aneurysm9** [comment]
It used to be that way, but [was changed](https://github.com/open-telemetry/opentelemetry-lambda/commit/e8109bfa0289cc3a6e853b5b2f12afa5f9879a6c) to allow the wrapper itself to be configured.  Perhaps there's a third way?

```sh
export NODE_OPTIONS="${OTEL_WRAPPER_OPTIONS} --require /opt/wrapper.js ${NODE_OPTIONS}"
```
