### ISSUE TITLE
Maintainer Acces Request - Aneurysm9

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-lambda-extension#295]
Changes in team composition and responsibilities have led to reduced or eliminated activity by AWS-based maintainers of this repository.  As the lead engineer on the team responsible for the AWS Distribution of OpenTelemetry (ADOT) and the ADOT Lambda layers I would like to be added to the @open-telemetry/lambda-extension-maintainers group (and this repository's [`CODEOWNERS` file](https://github.com/open-telemetry/opentelemetry-lambda/blob/main/.github/CODEOWNERS)).  We would like to increase our contributions to this part of the project and potentially resurrect the Lambda SIG meetings, but not having a maintainer on the team is an impediment.

**Comment by wangzlei** [comment]
I support @Aneurysm9 as maintainer of `opentelemetry-lambda`

**Comment by codeboten** [comment]
+1
