### ISSUE TITLE
Add support for node18.x runtime

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-lambda-extension#322]
The change https://github.com/open-telemetry/opentelemetry-lambda/pull/318 has been reverted in https://github.com/open-telemetry/opentelemetry-lambda/pull/321, adding an issue to track the work to bring it back once it is supported in the terraform module: https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/382

**Comment by vasireddy99** [comment]
This is a great call out. Upon looking at the recent correspondence the work can be resumed on this issue. I will take that action item and make some progress. Unless there are any other unknowns.

**Comment by eddie-atkinson** [comment]
My team and I have recently switched to using Node18 in production. It would be great to get support for OTel so we can get more observability in our stack.

**Comment by tylerbenson** [comment]
Looks like we cover 16, 18, and 20 now:
https://github.com/open-telemetry/opentelemetry-lambda/blob/main/.github/workflows/release-layer-nodejs.yml#L74
