### ISSUE TITLE
Add tsloughter to repo approvers

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-lambda-extension#447]
As part of the effort to bootstrap approvers in this repository, I'd like to nominate [tsloughter](https://github.com/tsloughter) for approver. He's been involved in OpenTelemetry for a long time and has is planning on getting involved w/ the lambda effort.

**Comment by Aneurysm9** [comment]
I approve of this plan.

**Comment by codeboten** [comment]
@tsloughter i've added you to the approvers github team. welcome aboard :)

**Comment by tsloughter** [comment]
Woo :clap:
