### ISSUE TITLE
Improve nodejs layer by auto-instrumentations-node

### ISSUE THREAD

**Issue by wangzlei** [open-telemetry/opentelemetry-lambda-extension#448]
**Describe the bug**
onboard [auto-instrumentations-node](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/metapackages/auto-instrumentations-node) instead of managing a library instrumentation list in https://github.com/open-telemetry/opentelemetry-lambda/blob/main/nodejs/packages/layer/src/wrapper.ts

Refer to python wrapper improvement https://github.com/open-telemetry/opentelemetry-lambda/pull/164

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
No need manage a lib instrumentation list in wrapper.ts
Load lib instrumentation by [auto-instrumentations-node](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/metapackages/auto-instrumentations-node)

**What did you see instead?**

**What version of collector/language SDK version did you use?**
Version: (e.g., `v0.58.0`, `v1.11.0`, etc)

**What language layer did you use?**
Config: (e.g., `Java`, `Python`, etc)

**Additional context**

**Comment by mat-rumian** [comment]
@wangzlei I could take care of it :)

**Comment by tylerbenson** [comment]
@mat-rumian do you still want to take care of this?  Feel free.

**Comment by serkan-ozal** [comment]
@tylerbenson do we still need to keep this issue open? Node.js layer already has auto instrumentation support with its own `wrapper.js` and replacing it with `@opentelemetry/auto-instrumentations-node` might come with additional coldstarts which we are trying to minimize
