### ISSUE TITLE
Metric exporting is turned-off by default

### ISSUE THREAD

**Issue by sasha-wing** [open-telemetry/opentelemetry-lambda-extension#475]
**Describe the bug**
[Metric exporting is turned-off by default](https://github.com/open-telemetry/opentelemetry-lambda/blob/main/python/src/otel/otel_sdk/otel-instrument#L99)

This is super confusing and un-documented.

Caused me to spend multiple hours to understand why my metrics are not reaching the embedded collector.

Related to the issue https://github.com/aws-observability/aws-otel-lambda/issues/439

**Comment by vasireddy99** [comment]
Hi thanks for providing more response. We are currently working on to make respective changes.
