### ISSUE TITLE
Node wrapper does not configure MeterProvider

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-lambda-extension#533]
**Describe the bug**
When using the Node JS layer the wrapper script configures a TracerProveder, but does not configure a MeterProvider, which results in metrics not being exported as expected.

**Steps to reproduce**
Use Node JS layer with a metrics pipeline and logging exporter configured on the collector extension.

**What did you expect to see?**
Metrics logged by the logging exporter.

**What did you see instead?**

```
2023-02-28T18:27:00.096Z	1861b109-499b-4ab7-ab63-2f87a71e26d3	ERROR	Metrics may not be exported for the lambda function because we are not force flushing before callback.
```

**What version of collector/language SDK version did you use?**

`arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-nodejs-amd64-ver-1-9-1:1` includes collector v0.70.0, though that's irrelevant as metrics never reach the collector extension.

**What language layer did you use?**

Node JS

**Comment by serhii-baksheiev** [comment]
Same error here

**Comment by JoaquinFernandez** [comment]
I also have the same error

**Comment by mat-rumian** [comment]
Hello everyone,
I've prepared a PR fixing the issue, please see https://github.com/open-telemetry/opentelemetry-lambda/pull/654
