### ISSUE TITLE
Remove Terraform Integration test script

### ISSUE THREAD

**Issue by vasireddy99** [open-telemetry/opentelemetry-lambda-extension#643]
**Describe the bug**
The Integration-tests scripts that exists in this repo are currently not used. but these scripts are used in in the [aws-otel-lambda](https://github.com/aws-observability/aws-otel-lambda) distribution for the integration testing, the aws-otel-lambda use this whole repo as a sub module. This issue is created to bring this discussion into light whether to port over this script to aws-otel-lambda repo completely or determine if these scripts can be used for integ tests for this repo.

**Comment by codeboten** [comment]
Until there's a need for tf files in this repo, my vote is to remove them here.
