### ISSUE TITLE
Rename OPENTELEMETRY_COLLECTOR_CONFIG_FILE to appropriate usage

### ISSUE THREAD

**Issue by vasireddy99** [open-telemetry/opentelemetry-lambda-extension#645]
Currently `OPENTELEMETRY_COLLECTOR_CONFIG_FILE` is a environment variable used to set the config file from any of the config map providers such as [http, s3, yaml.](https://github.com/open-telemetry/opentelemetry-lambda/blob/main/collector/internal/collector/collector.go#L60) etc., as per the naming convention it is not exactly a file as the input to this variable could be URI format example [here](https://github.com/open-telemetry/opentelemetry-lambda/tree/main/collector#configuration). Hence creating this issue to see if this can be renamed to `OPENTELEMETRY_COLLECTOR_CONFIG` instead.

**Comment by Aneurysm9** [comment]
I would suggest using `OPENTELEMETRY_COLLECTOR_CONFIG_URI` as the name of the variable to hold a URI pointing to a collector config.

We should ensure that we continue to support the prior variable for some period of time as a fallback if the new variable is not populated.  We should emit a warning into the logs if the old variable is used.

**Comment by gshpychka** [comment]
Still relevant. The name cause some confusion for me initially.

**Comment by tylerbenson** [comment]
Certainly open to PRs if someone wants to contribute this change.  LMK and I can reopen the issue.

**Comment by gshpychka** [comment]
> Certainly open to PRs if someone wants to contribute this change. LMK and I can reopen the issue.

Would the original name have to be kept for backwards compatibility?

**Comment by tylerbenson** [comment]
Assuming that would not be difficult, I'd say yes.

**Comment by gshpychka** [comment]
> Assuming that would not be difficult, I'd say yes.

What's the process for deprecating env vars in this case?

**Comment by tylerbenson** [comment]
We don't have any documented process. I would mainly suggest remove it from the documentation so people start using the new one going forward.

**Comment by gshpychka** [comment]
@tylerbenson can you reopen this issue so that it can be properly closed as complete if/when my PR is merged?

**Comment by gshpychka** [comment]
@tylerbenson thanks! Here is my PR: #1521
