### ISSUE TITLE
Nodejs wrapper layer not producing traces for basic lambda

### ISSUE THREAD

**Issue by sgracias1** [open-telemetry/opentelemetry-lambda-extension#686]
**Describe the bug**
The instrumentation layer for Nodejs does not seem to produce a trace when a HTTP request is received by the lambda

**Steps to reproduce**

1. Create a new lambda
2. Add nodejs instrumentation layer (compiled from this repo)
3. Set environment variable to point to wrapper (AWS_LAMBDA_EXEC_WRAPPER)
4. issue request to lambda

**What did you expect to see?**
Expected to see a trace in the Cloudwatch logs

**What did you see instead?**

```
Function Logs
Registering OpenTelemetry
@opentelemetry/api: Registered a global for diag v1.4.1.
AwsLambdaDetector found resource. Resource {
_attributes: {
'cloud.provider': 'aws',
'cloud.platform': 'aws_lambda',
'cloud.region': 'us-west-2',
'faas.name': 'sid-otel-nodejs',
'faas.version': '$LATEST'
},
}
... snip ...
@opentelemetry/api: Registered a global for trace v1.4.1.
@opentelemetry/api: Registered a global for context v1.4.1.
Applying patch for net module
2023-05-12T20:50:10.319Z	undefined	DEBUG	@opentelemetry/instrumentation-http Applying patch for http@18.15.0
START RequestId: 6ac876c6-8496-49bc-a1a1-4daf8eaf3445 Version: $LATEST
< Should be trace logs here?>
END RequestId: 6ac876c6-8496-49bc-a1a1-4daf8eaf3445
REPORT RequestId: 6ac876c6-8496-49bc-a1a1-4daf8eaf3445	Duration: 6.42 ms	Billed Duration: 7 ms	Memory Size: 128 MB	Max Memory Used: 114 MB	Init Duration: 1165.34 ms	
```

**What version of collector/language SDK version did you use?**
Latest version compiled from codebase

**What language layer did you use?**
Nodejs 18

**Comment by cartersocha** [comment]
Cc @martinkuba

**Comment by martinkuba** [comment]
@sgracias1 Make sure that X-Ray is enabled for your function, otherwise no traces will be sampled. Or, you can override the sampler using the `OTEL_TRACES_SAMPLER` env variable.

**Comment by sgracias1** [comment]
@martinkuba thank you for the pointer. I enabled X-Ray but still don't see any trace logs
`Registering OpenTelemetry
EXTENSION	Name: collector	State: Ready	Events: [INVOKE, SHUTDOWN]
START RequestId: 3693e891-613c-4e10-b03e-9922bd580ece Version: $LATEST
END RequestId: 3693e891-613c-4e10-b03e-9922bd580ece
REPORT RequestId: 3693e891-613c-4e10-b03e-9922bd580ece	Duration: 1097.60 ms	Billed Duration: 1098 ms	Memory Size: 128 MB	Max Memory Used: 128 MB	Init Duration: 1457.68 ms	
XRAY TraceId: 1-647f993c-5c3ee9f01b52f4815d99ddeb	SegmentId: 43ae2c134ce42ffc	Sampled: true`

Anything else I might be missing?

**Comment by sgracias1** [comment]
@martinkuba I did get the sample app in the repo uploaded through terraform working, so this seems like an issue with my application. I will close this ticket out and investigate the difference
