### ISSUE TITLE
[Question] How to configure HTTP instead of XRay

### ISSUE THREAD

**Issue by pradeepkusingh** [open-telemetry/opentelemetry-lambda-extension#835]
**Is your feature request related to a problem? Please describe.**
I have nodejs and java based lambdas, and trying to instrument those using OTEL layers/extension, unable to override the XRAY config I would like to send all trace data to a HTTP jager endpoint, unable to do so. please help.

**Describe the solution you'd like**
 Trace data should go to my HTTP endpoint

**Describe alternatives you've considered**
NA

**Additional context**

**Comment by tylerbenson** [comment]
XRay propagation is important for context propagation over aws services.  See here for more details:
https://github.com/open-telemetry/semantic-conventions/blob/main/docs/non-normative/compatibility/aws.md#context-propagation

When using regular http clients to make requests, the global propagator should still be supported.

**Comment by serkan-ozal** [comment]
@pradeepkusingh Sorry, but I am unable to understand the problem here. Why you are not able to export traces to HTTP endpoint because of XRay? Are you mentioning about context propagation issue or something different?
