### ISSUE TITLE
failing bash run.sh with the Error: Failed to create changeset for the stack: otel-stack

### ISSUE THREAD

**Issue by Ankireddykatha** [open-telemetry/opentelemetry-lambda-extension#885]
I have cloned this repository and executed **bash run.sh** inside the python/src
so getting below error, please someone help me on this

`Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Validate SAM template: sam validate
[*] Invoke Function: sam local invoke
[*] Test Function in the Cloud: sam sync --stack-name {{stack-name}} --watch
[*] Deploy: sam deploy --guided
requirements.txt file not found. Continuing the build without dependencies.
Running PythonPipBuilder:CopySource

		Managed S3 bucket: aws-sam-cli-managed-default-samclisourcebucket-1nmx9tuywxyv3
		A different default S3 bucket can be set in samconfig.toml
		Or by specifying --s3-bucket explicitly.
	Uploading to 44f1c9e389df98dc7ac2571ec1d62bc9  4740165 / 4740165  (100.00%)
File with same data already exists at d41d8cd98f00b204e9800998ecf8427e, skipping upload                                                                                                                               

	Deploying with following values
	===============================
	Stack name                   : otel-stack
	Region                       : us-east-2
	Confirm changeset            : False
	Disable rollback             : False
	Deployment s3 bucket         : aws-sam-cli-managed-default-samclisourcebucket-1nmx9tuywxyv3
	Capabilities                 : ["CAPABILITY_NAMED_IAM"]
	Parameter overrides          : {"LayerName": "otel-layer"}
	Signing Profiles             : {}

Initiating deployment
=====================

	Uploading to e3923bf6561faeb8f3b8d3f61952f3cd.template  1645 / 1645  (100.00%)
Error: Failed to create changeset for the stack: otel-stack, An error occurred (ValidationError) when calling the CreateChangeSet operation: Stack:arn:aws:cloudformation:us-east-2:xxxxxxxxxx:stack/otel-stack/eb491630-3fff-11ee-9b09-06c7098755f1 is in ROLLBACK_COMPLETE state and can not be updated.`

**Comment by serkan-ozal** [comment]
Hi @Ankireddykatha, seems that CloudFormation stack is not in correct state to make the deployment. Can you retry by deleting the stack from AWS CloudFormation console and re-initiating deployment?
